@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.grid.vampiresdelight.common;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;