@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.grid.vampiresdelight.client.extension;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;