@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.grid.vampiresdelight.client.particle;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;