@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.grid.vampiresdelight.common.advancement;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;